name: check_code_quality
on : pull_request
jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run black
        run: |
          black --check --verbose .